#!/data/data/com.aidlux/files/usr/bin/sh
export CLASSPATH=/data/data/com.aidlux/files/usr/libexec/termux-x11/starter.apk
unset LD_LIBRARY_PATH LD_PRELOAD
exec /system/bin/app_process / com.termux.x11.starter.Starter "$@"
